import assert from 'node:assert/strict'
import fs from 'node:fs'
import { chromium, expect } from '@playwright/test'

const base = process.env.READER_URL || 'http://127.0.0.1:8084/aposd2e-zh'
const output = process.env.READER_SHOTS || '/tmp/aposd2e-reader-interactions'
fs.mkdirSync(output, { recursive: true })
const browser = await chromium.launch({
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  headless: true,
})
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: 'light' })
const page = await context.newPage()
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
page.on('console', (message) => { if (message.type() === 'error') errors.push(`${message.text()} ${message.location().url}`) })
page.on('response', (response) => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
const settings = () => page.getByRole('button', { name: '阅读设置', exact: true })
const ready = async () => {
  await page.locator('.chapter-guide[data-diagram="ch04-common-path"][data-diagram-ready="true"]').waitFor()
  await page.evaluate(() => document.fonts.ready)
}
const noOverflow = async () => {
  const bounds = await page.evaluate(() => [innerWidth, document.documentElement.scrollWidth])
  assert.ok(bounds[1] <= bounds[0] + 1, `Document overflow ${bounds}`)
}
try {
  await page.goto(`${base}/ch04.html`, { waitUntil: 'networkidle' })
  await ready()
  await expect(page.locator('#reader-toc a')).toHaveCount(8)
  await settings().focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '减小字号', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('checkbox', { name: '原图用 SVG 显示', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(settings()).toBeFocused()
  await page.screenshot({ path: `${output}/desktop.png` })
  const original = page.locator('[data-figure="00012"]')
  await expect(original).toHaveAttribute('data-figure-mode', 'svg')
  await original.scrollIntoViewIfNeeded()
  await original.getByRole('button', { name: '放大原图', exact: true }).click()
  const modal = page.locator('dialog[open]')
  await expect(modal.locator('.diagram-canvas svg')).toBeVisible()
  await modal.getByRole('button', { name: '缩小', exact: true }).click()
  const firstScale = await modal.locator('output').textContent()
  await modal.getByRole('button', { name: '放大', exact: true }).click()
  assert.notEqual(await modal.locator('output').textContent(), firstScale)
  await modal.getByRole('button', { name: '适应窗口', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await modal.getByRole('button', { name: '下载 SVG', exact: true }).click()
  assert.equal((await downloadPromise).suggestedFilename(), '00012.svg')
  await page.screenshot({ path: `${output}/vector-modal.png` })
  await page.keyboard.press('Escape')
  await expect(page.locator('dialog[open]')).toHaveCount(0)
  await expect(original.getByRole('button', { name: '放大原图', exact: true })).toBeFocused()
  await settings().click()
  await page.getByRole('checkbox', { name: '原图用 SVG 显示', exact: true }).uncheck()
  await page.keyboard.press('Escape')
  await expect(original).toHaveAttribute('data-figure-mode', 'original')
  await original.locator('.original-raster img').evaluate((image) => {
    image.addEventListener('medium-zoom:opened', () => { image.dataset.zoomReady = 'true' }, { once: true })
  })
  await original.getByRole('button', { name: '放大原图', exact: true }).click()
  await expect(original.locator('.original-raster img')).toHaveAttribute('data-zoom-ready', 'true')
  await expect(page.locator('.medium-zoom-image--opened')).toBeVisible()
  await page.screenshot({ path: `${output}/raster-zoom.png` })
  await page.keyboard.press('Escape')
  await expect(page.locator('.medium-zoom-image--opened')).toHaveCount(0)
  await page.reload({ waitUntil: 'networkidle' })
  await ready()
  await expect(original).toHaveAttribute('data-figure-mode', 'original')
  await settings().click()
  await page.getByRole('checkbox', { name: '原图用 SVG 显示', exact: true }).check()
  await page.getByRole('button', { name: '增大字号', exact: true }).click()
  await page.getByRole('button', { name: '切换浅色或深色', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('html')).toHaveAttribute('data-reader-theme', 'dark')
  await page.waitForFunction(() => ['HTML', 'BODY'].every((tag) =>
    getComputedStyle(document.querySelector(tag)).backgroundColor === 'rgb(25, 25, 25)'))
  await page.locator('.reader-code-switch').getByRole('button', { name: 'Python', exact: true }).click()
  const code = page.locator('[data-example="ch04-f2"]')
  await expect(code).toHaveAttribute('data-code-mode', 'python')
  await expect(code.locator('.code-example-note')).toHaveCSS('font-size', '12px')
  await expect(page.locator('#content > p code').filter({ hasText: /^data$/ }).first()).toHaveCSS('background-color', 'rgb(36, 36, 36)')
  await code.scrollIntoViewIfNeeded()
  await page.screenshot({ path: `${output}/python-dark.png` })
  await code.getByRole('button', { name: '原例', exact: true }).click()
  await expect(code).toHaveAttribute('data-code-mode', 'original')
  await page.locator('.reader-code-switch').getByRole('button', { name: '原例', exact: true }).click()
  await page.locator('.reader-code-switch').getByRole('button', { name: 'Python', exact: true }).click()
  await expect(code).toHaveAttribute('data-code-mode', 'python')
  const guide = page.locator('[data-diagram="ch04-common-path"]')
  await guide.getByRole('button', { name: '放大图解', exact: true }).click()
  await expect(modal.locator('.diagram-canvas svg')).toBeVisible()
  const duplicates = await page.evaluate(() => {
    const ids = [...document.querySelectorAll('[id]')].map((element) => element.id)
    return ids.filter((id, index) => ids.indexOf(id) !== index)
  })
  assert.deepEqual(duplicates, [])
  await page.keyboard.press('Escape')
  await expect(guide.getByRole('button', { name: '放大图解', exact: true })).toBeFocused()
  await page.setViewportSize({ width: 390, height: 844 })
  await guide.locator('.diagram-stage[data-layout="mobile"]').waitFor()
  await noOverflow()
  await guide.scrollIntoViewIfNeeded()
  await page.screenshot({ path: `${output}/mobile-guide.png` })
  await page.getByRole('button', { name: '章节目录', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜索全书', exact: true }).fill('复杂性')
  await expect(page.locator('.reader-search-results a').first()).toBeVisible()
  await page.screenshot({ path: `${output}/mobile-search.png` })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '本章目录', exact: true }).click()
  await expect(page.locator('#reader-toc')).toBeVisible()
  await expect(page.locator('#reader-toc a[aria-current="location"]')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '本章目录', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '本章目录', exact: true }).click()
  await page.locator('#reader-toc a').last().click()
  await expect(page).toHaveURL(/#_4-8-/)
  await noOverflow()
  await page.getByRole('combobox', { name: '阅读语言', exact: true }).selectOption('zh-tw')
  await expect(page).toHaveURL(/zh-tw\/ch04.html/)
  await page.locator('[data-diagram="ch04-common-path"][data-diagram-ready="true"]').waitFor()
  await expect(page.locator('[data-example="ch04-f2"]')).toHaveAttribute('data-code-mode', 'python')
  await noOverflow()
  await page.screenshot({ path: `${output}/traditional-mobile.png` })
  await page.goto(`${base}/ch10.html`, { waitUntil: 'networkidle' })
  await page.locator('[data-figure="00020"]').scrollIntoViewIfNeeded()
  await noOverflow()
  const wide = await page.locator('[data-figure="00020"] .original-vector-scroll').evaluate((element) => ({
    scroll: element.scrollWidth, client: element.clientWidth,
  }))
  const codeMetrics = await page.locator('[data-example="ch10-f1"] .code-example-python').evaluate((element) =>
    [...element.querySelectorAll('pre,pre code,[class*="line"]')].slice(0, 8).map((node) => ({
      tag: node.tagName, class: node.className, font: getComputedStyle(node).fontSize,
      lineHeight: getComputedStyle(node).lineHeight, height: node.getBoundingClientRect().height,
    })))
  assert.ok(wide.scroll > wide.client, 'Wide original diagram should scroll internally')
  await page.screenshot({ path: `${output}/wide-original-mobile.png` })
  await page.goto(`${base}/ch13.html`, { waitUntil: 'networkidle' })
  const mixed = page.locator('[data-example="ch13-f5"]')
  await mixed.getByRole('button', { name: '原例', exact: true }).click()
  await expect(mixed.locator('.code-example-label')).toHaveText('C++ / Java')
  const extraLabel = await mixed.locator('.code-example-original div[class*="language-"]').evaluate((node) => getComputedStyle(node, '::before').display)
  assert.equal(extraLabel, 'none')
  await page.goto(`${base}/zh-tw/ch17.html`, { waitUntil: 'networkidle' })
  await expect(page.locator('#content')).toContainText('程式碼通過檢查後才能提交到儲存庫')
  for (const locale of ['', 'zh-tw/']) {
    await page.goto(`${base}/${locale}ch04.html`, { waitUntil: 'networkidle' })
    await ready()
    const reference = page.locator('.reader-footnote-reference a').first()
    const noteId = (await reference.getAttribute('href')).slice(1)
    const note = page.locator(`[id="${noteId}"]`)
    await reference.focus()
    await page.keyboard.press('Enter')
    await expect(note).toBeFocused()
    await expect(note).toBeInViewport({ ratio: 0.5 })
    await page.screenshot({ path: `${output}/footnote-${locale ? 'tw' : 'zh'}.png` })
    await note.locator('.reader-footnote-backref').focus()
    await page.keyboard.press('Enter')
    await expect(reference).toBeFocused()
    await expect(reference).toBeInViewport()
    await page.goto(`${base}/${locale}ch08.html`, { waitUntil: 'networkidle' })
    await page.getByRole('link', { name: /第 6\.3 [节節]/ }).click()
    await expect(page).toHaveURL(/#section-6-3$/)
    await expect(page.locator('#section-6-3').locator('..')).toBeInViewport({ ratio: 1 })
    await page.screenshot({ path: `${output}/section-${locale ? 'tw' : 'zh'}.png` })
  }
  assert.deepEqual(errors, [])
  fs.writeFileSync(`${output}/result.json`, JSON.stringify({ errors, duplicates, wide, codeMetrics, result: 'passed' }, null, 2))
  console.log(JSON.stringify({ result: 'passed', screenshots: output }))
} catch (error) {
  await page.screenshot({ path: `${output}/failure.png` }).catch(() => {})
  fs.writeFileSync(`${output}/result.json`, JSON.stringify({ errors, url: page.url(), failure: String(error) }, null, 2))
  throw error
} finally { await browser.close() }
